### PR TITLE
fix: type context, components in SliceZoneProps

### PR DESCRIPTION
**Pull request by Vorseek**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix types context in components props, for SliceZone

## Checklist:

- [ ] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

cat

### CODE REVIEW

**Comment by angeloashmore** [comment]
Thanks for the fix, @Vorseek! 😸

This will be published in the next release.

**Comment by dturkington49** [comment]
Currently blocked by this issue. Is a release possible in the coming days?

**Comment by angeloashmore** [comment]
Hi @dturkington49, thanks for the reminder. I was waiting to bundle this fix with other changes, but we haven't had to fix anything since this bug.

I just published it as `v2.4.3`. You should be able to update to the latest version with the following command:

```sh
npm install @prismicio/react@latest
```

If that doesn't fix your issue, please let me know by opening a new issue or commenting here. Thanks! 🙂

**Comment by dturkington49** [comment]
@angeloashmore Wow, thanks for the quick response! Upgraded to 2.4.3 and I'm unblocked. Thank you!

**Pull request merged**
